#!/usr/bin/env python3
"""Turn a Genus cell report into the key/value table PpaModel::loadFromFile reads.

This is the seam between the analytical model and real synthesis data. The
selection code does not change -- it just gets better numbers.

  genus> report_area -detail > area.rpt
  python3 tools/parse_genus.py area.rpt > ppa_model.txt
  ...
  TPI 32 out.ckt out.csv -ppa ppa_model.txt

WARNING: written against the documented report layout and exercised only on
the sample in tests/data. It has never been run against a real Genus install,
because this project was built on a machine with no Cadence licence. Check the
numbers before trusting them.
"""

import argparse
import re
import sys
from collections import defaultdict

# Which library cells feed which knob in the model. Drive strength is stripped
# before matching, so NAND2_X1 and NAND2_X4 both land on nand2.
CELL_PATTERNS = {
    "inv":   re.compile(r"^(INV|NOT)\d*$", re.I),
    "buf":   re.compile(r"^BUFF?\d*$", re.I),
    "nand2": re.compile(r"^NAND2$", re.I),
    "nor2":  re.compile(r"^NOR2$", re.I),
    "and2":  re.compile(r"^AND2$", re.I),
    "or2":   re.compile(r"^OR2$", re.I),
    "xor2":  re.compile(r"^XOR2$", re.I),
}

DRIVE = re.compile(r"_X\d+$|_\d+X$", re.I)


def classify(cell):
    base = DRIVE.sub("", cell.split("/")[-1])
    for key, pat in CELL_PATTERNS.items():
        if pat.match(base):
            return key
    return None


def find_columns(header):
    """Maps a report header to the indices of the columns worth reading.

    Column labels have spaces in them ("Cell Area"), so the header splits on
    runs of whitespace while the data rows split on any whitespace. Returns
    indices into a data row, where index 0 is the cell name.
    """
    names = re.split(r"\s{2,}", header.strip())
    cols = {}
    for i, name in enumerate(names):
        low = name.lower()
        if low in ("cell area", "area", "total area"):
            cols.setdefault("area", i)
        elif low == "delay" or low.startswith("delay"):
            cols.setdefault("delay", i)
    return cols


def parse(lines):
    """Collects per-cell area and delay, averaging over drive strengths."""
    areas = defaultdict(list)
    delays = defaultdict(list)
    cols = {}

    for raw in lines:
        line = raw.rstrip("\n")
        stripped = line.strip()
        if not stripped or set(stripped) <= set("-=# "):
            continue

        # The header names the columns; without it there is no way to tell a
        # cell count from an area, so bail rather than guess.
        if not cols and re.search(r"area", stripped, re.I):
            cols = find_columns(line)
            if "area" in cols:
                continue

        parts = stripped.split()
        if len(parts) < 2:
            continue
        key = classify(parts[0])
        if key is None:
            continue
        if "area" not in cols:
            continue

        def numeric(idx):
            if idx is None or idx >= len(parts):
                return None
            try:
                return float(parts[idx])
            except ValueError:
                return None

        area = numeric(cols.get("area"))
        if area is not None:
            areas[key].append(area)
        delay = numeric(cols.get("delay"))
        if delay is not None:
            delays[key].append(delay)

    if not cols:
        raise SystemExit("no column header found -- is this a Genus area report?")
    return areas, delays


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("report", help="Genus report file, or - for stdin")
    ap.add_argument("-o", "--output", default=None)
    args = ap.parse_args()

    lines = sys.stdin if args.report == "-" else open(args.report)
    with lines if args.report != "-" else sys.stdin as f:
        areas, delays = parse(f)

    if not areas:
        sys.exit("no recognisable cells in the report -- check the format")

    out = ["# generated by tools/parse_genus.py from " + args.report]
    for key in sorted(areas):
        out.append(f"{key}_area {sum(areas[key]) / len(areas[key]):.4f}")
    for key in sorted(delays):
        if delays[key]:
            out.append(f"{key}_delay {sum(delays[key]) / len(delays[key]):.4f}")

    text = "\n".join(out) + "\n"
    if args.output:
        with open(args.output, "w") as f:
            f.write(text)
        print(f"wrote {args.output}", file=sys.stderr)
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
